// Generated by CoffeeScript 1.6.3
(function() {
  var Divebar;

  Divebar = function() {
    var SCRNH, SCRNW, append_padding, getX, getY;
    SCRNH = window.screen.height;
    SCRNW = window.screen.width;
    $(function() {
      return $('body > *').wrapAll("<div id='dive-div' />");
    });
    $(function() {
      return $('#dive-div').css('position', "relative");
    });
    $(function() {
      return $('#dive-div').wrapAll("<div id='dive-div2' />");
    });
    getX = function() {
      var knownX;
      knownX = window.screenLeft;
      return knownX != null ? knownX : knownX = window.screenX;
    };
    getY = function() {
      var knownY;
      knownY = window.screenTop;
      return knownY != null ? knownY : knownY = window.screenY;
    };
    append_padding = function(x, y) {
      var h, w, wrapDiv;
      wrapDiv = $('#dive-div2');
      w = window.outerWidth;
      h = window.outerHeight;
      if (x + w > SCRNW) {
        wrapDiv.css('padding-right', (x + w - SCRNW) + "px");
        wrapDiv.css('width', '100%');
      } else {
        wrapDiv.css('padding-right', "0px");
      }
      if (y + h > SCRNH) {
        wrapDiv.css('padding-bottom', (y + h - SCRNH) + "px");
      } else {
        wrapDiv.css('padding-bottom', "0px");
      }
      if (x < 0) {
        wrapDiv.css('padding-left', (-x) + "px");
        wrapDiv.css('positon', 'relative');
        return wrapDiv.css('width', '100%');
      } else {
        return wrapDiv.css('padding-left', "0px");
      }
    };
    return setInterval(function() {
      var knownX, knownY;
      if (knownX !== getX() || knownY !== getY()) {
        knownX = getX();
        knownY = getY();
        return append_padding(knownX, knownY);
      }
    }, 200);
  };

  Divebar();

}).call(this);
